name: nyc_taxi
version: "1.0.0"
config-version: 2

profile: nyc_taxi

model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["tests"]
macro-paths: ["macros"]

target-path: "target"
clean-targets: ["target", "dbt_packages"]

models:
  nyc_taxi:
    staging:
      +schema: staging
      +materialized: view
    marts:
      +schema: mart
      +materialized: table

seeds:
  nyc_taxi:
    +schema: raw
